# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020aba6ad43fdedf8ec9b878b16d0c238ddf879b6edec5a4ee30ed95204a6f93ecfdb6d065bd0f0f5b1b8e785218656d676c602fd28efa7161f9c499db995d86

test:
  secret_key_base: a1fe035cccda055c510f99f0f49dfe0287b0b1086a86cead27f7cec8f62dd1c4febeeec5990da72f5a1a5996035a918edbd902e30aec1680312240de1f78812e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
